apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  # namespace는 적지 마세요 (kustomization.yaml의 설정을 따름)
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: final-project-dev
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  rules:
  - host: dev.petclinic.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-service
            port:
              number: 80
