apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# ì—¬ê¸°ì„œ ë³„ëª…ì„ ì§„ì§œ ECR ì£¼ì†Œë¡œ ë§¤í•‘
images:
- name: petclinic-image-placeholder
  newName: 639242342449.dkr.ecr.ap-northeast-2.amazonaws.com/gitactions
  newTag: latest  # ğŸ‘ˆ CIê°€ ì´ ë¶€ë¶„ì„ ê³„ì† ìˆ˜ì •í•˜ê²Œ ë©ë‹ˆë‹¤.
