apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-was
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: petclinic
        image: petclinic-image-placeholder  # ğŸ‘ˆ ì—¬ê¸°ê°€ í•µì‹¬! ë‚˜ì¤‘ì— ê°ˆì•„ë¼ì›€
        ports:
        - containerPort: 8080
