apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  # namespace 라인은 지우세요. kustomization.yaml에서 자동으로 넣어주는 게 좋습니다.
spec:
  # ingressClassName 삭제 (각 클라우드에서 따로 지정)
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-web-service
            port:
              number: 80
