apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress  # [중요] base의 ingress 이름과 토씨 하나 안 틀리고 똑같아야 함!
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-eks-alb-logs-hjh,access_logs.s3.prefix=ingress-log
    alb.ingress.kubernetes.io/actions.fixed-4xx: >
      {"type":"fixed-response","fixedResponseConfig":{"statusCode":"400","contentType":"text/plain","messageBody":"Intentional 400 Error for Testing"}}
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-web-service
            port:
              number: 80
      - path: /test-400
        pathType: Prefix
        backend:
          service:
            name: fixed-4xx
            port:
              name: use-annotation
